version: '3.9'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=darkside
      - DB_NAME=library
      - DB_PORT=5432

  db:
    image: "postgres:14.7-alpine"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: darkside
      POSTGRES_DB: library
    ports:
      - "25432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
